#!/bin/sh
cd "$(dirname "$0")/pre-commit.d"
for hook in *; do
	bash $hook
	RESULT=$?
	if [ $RESULT != 0 ]; then
		echo "pre-commit.d/$hook returned non-zero: $RESULT, abort checkout"
		exit $RESULT
	fi
done
exit 0
