name: test

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
          lfs: true
      - name: Nix Install
        uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=./nixpkgs
      - name: Nix Cache
        uses: cachix/cachix-action@v9
        with:
          name: lihop
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./build.sh
          #- name: GUT Tests
          #  run: |
          #    godot -d -s --path $PWD/game addons/gut/gut_cmdln.gd
          #- name: WAT Tests
          #  run: |
          #    godot --path $PWD/game addons/WAT/cli.tscn -run_all
